[package]
name = "cringe_word_rem"
version = "0.1.0"
authors = ["PrajwalCH <prajjwal2058@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.5.0"
